esphome:
  name: gaming-pokypow
  friendly_name: gaming-pokypow
  on_boot:
    priority: -100  # Lower priority to ensure it runs after boot is complete
    then:
      - light.turn_on:
          id: led_strip
          red: 0
          green: 100%
          blue: 0
          brightness: 50%

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
  flash_size: 4MB
  

# Enable logging
logger:
  # level: DEBUG

# Enable Home Assistant API
api:

  on_client_connected:
    then:
      - light.turn_on:
          id: led_strip
          red: 0
          green: 0
          blue: 100%
          brightness: 50%
  on_client_disconnected:
    then:
      - light.turn_on:
          id: led_strip
          red: 100%
          green: 100%
          blue: 0
          brightness: 50%
ota:
  - platform: esphome
    password: "9a276257164827a77c20a46ee176b36e"

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "PokyPow Setup"

captive_portal:
  
web_server:
  port: 80


light:
  - platform: neopixelbus
    type: GRBW
    variant: SK6812
    pin: GPIO5
    id: led_strip
    num_leds: 1
    name: "LED Strip"
    effects:
      - addressable_rainbow:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 2s


switch:

  - platform: factory_reset
    name: Restart with Factory Default Settings
  
  - platform: gpio
    pin: 
      number: GPIO7
      inverted: true
      mode:
        output: true
        pulldown: true
    id: power_pin
    internal: true

  - platform: gpio
    pin: 
      number: GPIO6
      inverted: true
      mode:
        output: true
        pulldown: true
    id: reset_pin
    internal: true

  - platform: template
    name: "Power Switch"
    id: power_switch
    internal: true
    turn_on_action:
      - switch.turn_on: power_pin
      - delay: 2000ms
      - switch.turn_off: power_pin

  - platform: template
    name: "Power Switch Force"
    id: power_switch_force
    internal: true
    turn_on_action:
      - switch.turn_on: power_pin
      - delay: 10000ms
      - switch.turn_off: power_pin

  - platform: template
    name: "Reset Switch"
    id: reset_switch
    internal: true
    turn_on_action:
      - switch.turn_on: reset_pin
      - delay: 1000ms
      - switch.turn_off: reset_pin


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO04
      mode:
        input: true
        pullup: true
      inverted: false
    id: pc_power_sensor
    name: "Power State"
    device_class: running
    icon: "mdi:desktop-classic"

button:
  - platform: template
    name: "Power Button"
    id: power_button
    icon: "mdi:power-standby"
    on_press:
      then:
        - switch.toggle: power_switch

  - platform: template
    name: "Force Power Off"
    id: force_power_off
    icon: "mdi:power-plug-off"
    on_press:
      then:
        - switch.toggle: power_switch_force
        - delay: 1000ms
        - switch.turn_off: power_switch_force

  - platform: template
    name: "Reset Button"
    id: reset_button
    icon: "mdi:restart"
    on_press:
      then:
        - switch.toggle: reset_pin



